name: Android CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        module: ["layback"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if files are changed
        uses: marceloprado/has-changed-path@v1
        id: has-changed-path
        with:
          paths: ${{ matrix.module }} .github/workflows

      - name: set up JDK 11
        if: steps.has-changed-path.outputs.changed == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        if: steps.has-changed-path.outputs.changed == 'true'
        run: chmod +x gradlew

      - name: Build
        if: steps.has-changed-path.outputs.changed == 'true'
        run: ./gradlew ${{ matrix.module }}:build

      - uses: r0adkll/sign-android-release@v1
        if: steps.has-changed-path.outputs.changed == 'true'
        name: Sign APK
        id: sign_apk
        with:
          releaseDirectory: ${{ matrix.module }}/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - uses: actions/upload-artifact@v3
        if: steps.has-changed-path.outputs.changed == 'true'
        with:
          name: ${{ matrix.module }}-release
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}
