name: Android CI

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        module: ["layback"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if files are changed
        uses: marceloprado/has-changed-path@v1
        id: has-changed-path
        with:
          paths: ${{ matrix.module }}

      - name: set up JDK 11
        if: steps.has-changed-path.outputs.changed == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        if: steps.has-changed-path.outputs.changed == 'true'
        run: chmod +x gradlew

      - name: Build
        if: steps.has-changed-path.outputs.changed == 'true'
        run: ./gradlew ${{ matrix.module }}:build
