name: PR Check

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"

  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**.md"

jobs:
  android-check:
    strategy:
      matrix:
        module: [ "layback", "websearch", "lockscreen", "notch", "weibolink" ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if files are changed
        uses: marceloprado/has-changed-path@v1
        id: has-changed-path
        with:
          paths: ${{ matrix.module }} .github/workflows

      - name: Set up JDK 17
        if: steps.has-changed-path.outputs.changed == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        if: steps.has-changed-path.outputs.changed == 'true'
        run: chmod +x gradlew

      - name: Build
        if: steps.has-changed-path.outputs.changed == 'true'
        run: ./gradlew ${{ matrix.module }}:check
