name: Release websearch

on:
  push:
    tags:
      - "websearch-v*.*.*"

jobs:
  call-release-app:
    uses: ./.github/workflows/release-app.yml
    with:
      module: websearch
    secrets: inherit
