name: Release layback

on:
  push:
    branches:
      - "workflow-test/**"
    tags:
      - "layback-v*.*.*"

jobs:
  call-release-app:
    uses: ./.github/workflows/release-app.yml
    with:
      module: layback
    secrets: inherit
