name: Release lockscreen

on:
  push:
    tags:
      - "lockscreen-v*.*.*"

jobs:
  call-release-app:
    uses: ./.github/workflows/release-app.yml
    with:
      module: lockscreen
    secrets: inherit
  upload-to-google-play:
    uses: ./.github/workflows/upload-to-google-play.yml
    with:
      module: lockscreen
      applicationId: io.github.wangcheng678.lockscreen
    secrets: inherit
