name: Build an app and add to release

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        if: steps.has-changed-path.outputs.changed == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew ${{ inputs.module }}:assembleRelease

      - name: Rename file
        run: mv ${{ inputs.module }}/build/outputs/apk/release/${{ inputs.module }}-release-unsigned.apk ${{ inputs.module }}/build/outputs/apk/release/${{ inputs.module }}-release-unsigned.apk

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: ${{ inputs.module }}/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Add file to release
        uses: djn24/add-asset-to-release@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}
