name: Release layback

on:
  workflow_dispatch:

  push:
    tags:
      - "layback-v*.*.*"

jobs:
  call-release-app:
    uses: ./.github/workflows/release-app.yml
    with:
      module: layback
    secrets: inherit
