name: Add layback apk and add to release

on:
  push:
    tags:
      - "layback-v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/release-app
        with:
          module: layback
