name: Build & Create Release

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
      applicationId:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build app bundle
        run: ./gradlew ${{ inputs.module }}:bundleRelease

      - name: Upload Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ${{ inputs.applicationId }}
          releaseFiles: ${{ inputs.module }}/build/outputs/bundle/release/${{ inputs.module }}-release.aab
          status: draft
